permits:
  store_staff_create: Может создавать сотрудника склада
  store_staff_update: Может редактировать сотрудника склада
  store_staff_list: Может получать список сотрудников склада
  store_staff_delete: Может удалять сотрудников склада
  store_staff_get: Может смотреть на сотрудников склада
  store_assign: Может назначать сотрудников на склад