declare module 'v-calendar'
declare module 'vue3-carousel'
declare module 'vue3-smooth-dnd'
declare module '@ckeditor/ckeditor5-vue'
declare module '@ckeditor/ckeditor5-build-classic'
declare module '@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.min.js'
