"""Initial

Revision ID: 78bd2880f779
Revises: 
Create Date: 2023-06-20 12:04:30.486732

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.user.models.user_models import UserType
from uuid import uuid4

# revision identifiers, used by Alembic.
revision = '78bd2880f779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create sequence companies_lsn_seq")
    op.execute("create sequence users_lsn_seq")
    op.execute("create sequence contractors_lsn_seq")
    op.execute("create sequence stores_lsn_seq")
    op.execute("create sequence servicesuppliers_lsn_seq")
    op.execute("create sequence manufacturers_lsn_seq")
    op.execute("create sequence assettypes_lsn_seq")
    op.execute("create sequence models_lsn_seq")
    op.execute("create sequence assets_lsn_seq")

    op.execute("create sequence assets_log_lsn_seq")
    op.execute("create sequence orders_lsn_seq")
    op.execute("create sequence orders_number_seq")
    op.execute("create sequence orders_lines_lsn_seq")
    op.create_table('companies',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True),
    sa.Column('locale', sqlalchemy_utils.types.locale.LocaleType(), nullable=True),
    sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_lsn'), 'companies', ['lsn'], unique=False)
    op.create_table('assettypes',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('type', sa.Unicode(length=20), nullable=False),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('serial_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assettypes_company_id'), 'assettypes', ['company_id'], unique=False)
    op.create_index(op.f('ix_assettypes_id'), 'assettypes', ['id'], unique=False)
    op.create_index(op.f('ix_assettypes_lsn'), 'assettypes', ['lsn'], unique=False)
    op.create_table('contractors',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_contractors_company_id'), 'contractors', ['company_id'], unique=False)
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_index(op.f('ix_contractors_lsn'), 'contractors', ['lsn'], unique=False)
    op.create_table('manufacturers',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_company_id'), 'manufacturers', ['company_id'], unique=False)
    op.create_index(op.f('ix_manufacturers_id'), 'manufacturers', ['id'], unique=False)
    op.create_index(op.f('ix_manufacturers_lsn'), 'manufacturers', ['lsn'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
    sa.Column('address', sa.Unicode(length=255), nullable=False),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_stores_company_id'), 'stores', ['company_id'], unique=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_lsn'), 'stores', ['lsn'], unique=False)
    op.create_table('models',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_lsn'), 'models', ['lsn'], unique=False)
    op.create_index(op.f('ix_models_manufacturer_id'), 'models', ['manufacturer_id'], unique=False)
    op.create_table('servicesuppliers',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_servicesuppliers_contractor_id'), 'servicesuppliers', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_servicesuppliers_id'), 'servicesuppliers', ['id'], unique=False)
    op.create_index(op.f('ix_servicesuppliers_lsn'), 'servicesuppliers', ['lsn'], unique=False)
    op.create_index(op.f('ix_servicesuppliers_store_id'), 'servicesuppliers', ['store_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True),
    sa.Column('locale', sqlalchemy_utils.types.locale.LocaleType(), nullable=True),
    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('nickname', sa.Unicode(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(UserType), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lsn'), 'users', ['lsn'], unique=False)
    op.create_index(op.f('ix_users_store_id'), 'users', ['store_id'], unique=False)
    op.create_table('assets',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('at_user_id', sa.UUID(), nullable=True),
    sa.Column('user_created_id', sa.UUID(), nullable=True),
    sa.Column('barcode', sa.Unicode(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['assettypes.id'], ),
    sa.ForeignKeyConstraint(['at_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_created_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type_id'), 'assets', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_assets_barcode'), 'assets', ['barcode'], unique=True)
    op.create_index(op.f('ix_assets_company_id'), 'assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_lsn'), 'assets', ['lsn'], unique=False)
    op.create_index(op.f('ix_assets_manufacturer_id'), 'assets', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_assets_model_id'), 'assets', ['model_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_store_id'), 'assets', ['store_id'], unique=False)
    op.create_table('assets_log',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Unicode(length=30), nullable=False),
    sa.Column('from_', sa.Unicode(length=255), nullable=True),
    sa.Column('to', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_log_asset_id'), 'assets_log', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_log_id'), 'assets_log', ['id'], unique=False)
    op.create_index(op.f('ix_assets_log_lsn'), 'assets_log', ['lsn'], unique=False)
    op.create_table('orders',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Unicode(length=30), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('user_created_id', sa.UUID(), nullable=True),
    sa.Column('supplier_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_created_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_asset_id'), 'orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_lsn'), 'orders', ['lsn'], unique=False)
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_orders_supplier_id'), 'orders', ['supplier_id'], unique=False)
    op.create_table('orders_lines',
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_lines_id'), 'orders_lines', ['id'], unique=False)
    op.create_index(op.f('ix_orders_lines_lsn'), 'orders_lines', ['lsn'], unique=False)
    op.create_index(op.f('ix_orders_lines_order_id'), 'orders_lines', ['order_id'], unique=False)

    op.execute("insert into companies (lsn, id, title, locale, country, currency, created_at, updated_at) VALUES (1, '5ad88cd8-0587-4f30-b568-bd2270adb999', 'Main', 'ru_RU', 'RU', 'RUB', now(), now())")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_lines_order_id'), table_name='orders_lines')
    op.drop_index(op.f('ix_orders_lines_lsn'), table_name='orders_lines')
    op.drop_index(op.f('ix_orders_lines_id'), table_name='orders_lines')
    op.drop_table('orders_lines')
    op.drop_index(op.f('ix_orders_supplier_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_lsn'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_asset_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_assets_log_lsn'), table_name='assets_log')
    op.drop_index(op.f('ix_assets_log_id'), table_name='assets_log')
    op.drop_index(op.f('ix_assets_log_asset_id'), table_name='assets_log')
    op.drop_table('assets_log')
    op.drop_index(op.f('ix_assets_store_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_model_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_manufacturer_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_lsn'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_company_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_barcode'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_store_id'), table_name='users')
    op.drop_index(op.f('ix_users_lsn'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_servicesuppliers_store_id'), table_name='servicesuppliers')
    op.drop_index(op.f('ix_servicesuppliers_lsn'), table_name='servicesuppliers')
    op.drop_index(op.f('ix_servicesuppliers_id'), table_name='servicesuppliers')
    op.drop_index(op.f('ix_servicesuppliers_contractor_id'), table_name='servicesuppliers')
    op.drop_table('servicesuppliers')
    op.drop_index(op.f('ix_models_manufacturer_id'), table_name='models')
    op.drop_index(op.f('ix_models_lsn'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_stores_lsn'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_company_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_manufacturers_lsn'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_id'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_company_id'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_contractors_lsn'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_company_id'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_assettypes_lsn'), table_name='assettypes')
    op.drop_index(op.f('ix_assettypes_id'), table_name='assettypes')
    op.drop_index(op.f('ix_assettypes_company_id'), table_name='assettypes')
    op.drop_table('assettypes')
    op.drop_index(op.f('ix_companies_lsn'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.execute("drop sequence companies_lsn_seq")
    op.execute("drop sequence users_lsn_seq")
    op.execute("drop sequence contractors_lsn_seq")
    op.execute("drop sequence stores_lsn_seq")
    op.execute("drop sequence servicesuppliers_lsn_seq")
    op.execute("drop sequence manufacturers_lsn_seq")
    op.execute("drop sequence assettypes_lsn_seq")
    op.execute("drop sequence models_lsn_seq")
    op.execute("drop sequence assets_lsn_seq")

    op.execute("drop sequence assets_log_lsn_seq")
    op.execute("drop sequence orders_lsn_seq")
    op.execute("drop sequence orders_number_seq")
    op.execute("drop sequence orders_lines_lsn_seq")
    # ### end Alembic commands ###
