"""init2

Revision ID: 7c3c9e87f204
Revises: 6ea1b38aba41
Create Date: 2024-10-20 09:49:19.439688

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7c3c9e87f204'
down_revision = '6ea1b38aba41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_bus_user_id'), 'bus', ['user_id'], unique=False)
    op.drop_index('ix_user_store_id', table_name='user')
    op.drop_constraint('user_store_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'store_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_store_id_fkey', 'user', 'store', ['store_id'], ['id'])
    op.create_index('ix_user_store_id', 'user', ['store_id'], unique=False)
    op.drop_index(op.f('ix_bus_user_id'), table_name='bus')
    op.drop_column('bus', 'user_id')
    # ### end Alembic commands ###