"""init3

Revision ID: eb1a7d885a6a
Revises: 7c3c9e87f204
Create Date: 2024-10-31 09:41:49.251784

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'eb1a7d885a6a'
down_revision = '7c3c9e87f204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_staff',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('staff_position', sa.Enum('STOREKEEPER', 'SENIOR_STOREKEEPER', 'DEPUTY_STORE_MANAGER', 'STORE_MANAGER', 'SUPERVISOR', name='staffposition'), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('store_ids', sa.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.Column('staff_number', sa.String(), nullable=True),
    sa.Column('external_number', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lsn', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_staff_company_id'), 'store_staff', ['company_id'], unique=False)
    op.create_index(op.f('ix_store_staff_external_number'), 'store_staff', ['external_number'], unique=False)
    op.create_index(op.f('ix_store_staff_id'), 'store_staff', ['id'], unique=False)
    op.create_index(op.f('ix_store_staff_lsn'), 'store_staff', ['lsn'], unique=False)
    op.create_index(op.f('ix_store_staff_staff_number'), 'store_staff', ['staff_number'], unique=False)
    op.create_index(op.f('ix_store_staff_staff_position'), 'store_staff', ['staff_position'], unique=False)
    op.create_index(op.f('ix_store_staff_store_id'), 'store_staff', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_staff_store_ids'), 'store_staff', ['store_ids'], unique=False)
    op.create_index(op.f('ix_store_staff_user_id'), 'store_staff', ['user_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("create sequence store_staff_lsn_seq")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_staff_user_id'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_store_ids'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_store_id'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_staff_position'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_staff_number'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_lsn'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_id'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_external_number'), table_name='store_staff')
    op.drop_index(op.f('ix_store_staff_company_id'), table_name='store_staff')
    op.drop_table('store_staff')
    # ### end Alembic commands ###
    op.execute("drop sequence store_staff_lsn_seq")
