"""initial

Revision ID: f9e0bfba8d29
Revises: 
Create Date: 2023-07-05 17:55:30.292231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'f9e0bfba8d29'
down_revision = '1e8431842d98'
branch_labels = None
depends_on = '1e8431842d98'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=False),
                    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
                    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True),
                    sa.Column('locale', sqlalchemy_utils.types.locale.LocaleType(), nullable=True),
                    sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('external_id')
                    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_lsn'), 'company', ['lsn'], unique=False)
    op.create_index(op.f('ix_company_title'), 'company', ['title'], unique=False)
    op.create_table('role',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=False),
                    sa.Column('parents', postgresql.ARRAY(sa.Uuid()), nullable=True),
                    sa.Column('permissions_allow', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('permissions_deny', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title', 'company_id', name='_role_company_id_uc')
                    )
    op.create_index(op.f('ix_role_company_id'), 'role', ['company_id'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_lsn'), 'role', ['lsn'], unique=False)
    op.create_index(op.f('ix_role_parents'), 'role', ['parents'], unique=False)
    op.create_index(op.f('ix_role_permissions_allow'), 'role', ['permissions_allow'], unique=False)
    op.create_table('store',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=False),
                    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
                    sa.Column('address', sa.Unicode(length=255), nullable=False),
                    sa.Column('source', sa.Unicode(length=20), nullable=False),
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('external_id')
                    )
    op.create_index(op.f('ix_store_company_id'), 'store', ['company_id'], unique=False)
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.create_index(op.f('ix_store_lsn'), 'store', ['lsn'], unique=False)
    op.create_table('uom_category',
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=False),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_uom_category_company_id'), 'uom_category', ['company_id'], unique=False)
    op.create_index(op.f('ix_uom_category_id'), 'uom_category', ['id'], unique=False)
    op.create_index(op.f('ix_uom_category_lsn'), 'uom_category', ['lsn'], unique=False)
    op.create_table('uom',
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=False),
                    sa.Column('category_id', sa.Uuid(), nullable=True),
                    sa.Column('type', sa.Unicode(length=30), nullable=False),
                    sa.Column('ratio', sa.Numeric(precision=12, scale=2), nullable=True),
                    sa.Column('precision', sa.Numeric(precision=12, scale=2), nullable=True),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['uom_category.id'], ),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_uom_company_id'), 'uom', ['company_id'], unique=False)
    op.create_index(op.f('ix_uom_id'), 'uom', ['id'], unique=False)
    op.create_index(op.f('ix_uom_lsn'), 'uom', ['lsn'], unique=False)
    op.create_index(op.f('ix_uom_type'), 'uom', ['type'], unique=False)
    op.create_table('user',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
                    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=True),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
                    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True),
                    sa.Column('locale', sqlalchemy_utils.types.locale.LocaleType(), nullable=True),
                    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
                              nullable=True),
                    sa.Column('nickname', sa.Unicode(length=255), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('type', sa.Unicode(length=255), nullable=False),
                    sa.Column('store_id', sa.Uuid(), nullable=True),
                    sa.Column('companies', postgresql.ARRAY(sa.Uuid()), nullable=True),
                    sa.Column('roles', postgresql.ARRAY(sa.Uuid()), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('external_id')
                    )
    op.create_index(op.f('ix_user_companies'), 'user', ['companies'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_lsn'), 'user', ['lsn'], unique=False)
    op.create_index(op.f('ix_user_roles'), 'user', ['roles'], unique=False)
    op.create_index(op.f('ix_user_store_id'), 'user', ['store_id'], unique=False)
    op.create_table('partner',
                    sa.Column('lsn', sa.BigInteger(), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=False),
                    sa.Column('type', sa.Unicode(length=30), nullable=False),
                    sa.Column('external_id', sa.Unicode(length=255), nullable=True),
                    sa.Column('parent_id', sa.Uuid(), nullable=True),
                    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
                              nullable=True),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
                    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True),
                    sa.Column('created_user_id', sa.Uuid(), nullable=False),
                    sa.Column('locale', sqlalchemy_utils.types.locale.LocaleType(), nullable=True),
                    sa.Column('currency', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False),
                    sa.Column('company_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('vars', sqlalchemy_utils.types.json.JSONType(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['parent_id'], ['partner.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('external_id')
                    )
    op.create_index(op.f('ix_partner_company_id'), 'partner', ['company_id'], unique=False)
    op.create_index(op.f('ix_partner_created_user_id'), 'partner', ['created_user_id'], unique=False)
    op.create_index(op.f('ix_partner_id'), 'partner', ['id'], unique=False)
    op.create_index(op.f('ix_partner_lsn'), 'partner', ['lsn'], unique=False)
    op.create_index(op.f('ix_partner_parent_id'), 'partner', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_parent_id'), table_name='partner')
    op.drop_index(op.f('ix_partner_lsn'), table_name='partner')
    op.drop_index(op.f('ix_partner_id'), table_name='partner')
    op.drop_index(op.f('ix_partner_created_user_id'), table_name='partner')
    op.drop_index(op.f('ix_partner_company_id'), table_name='partner')
    op.drop_table('partner')
    op.drop_index(op.f('ix_user_store_id'), table_name='user')
    op.drop_index(op.f('ix_user_roles'), table_name='user')
    op.drop_index(op.f('ix_user_lsn'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_companies'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_uom_type'), table_name='uom')
    op.drop_index(op.f('ix_uom_lsn'), table_name='uom')
    op.drop_index(op.f('ix_uom_id'), table_name='uom')
    op.drop_index(op.f('ix_uom_company_id'), table_name='uom')
    op.drop_table('uom')
    op.drop_index(op.f('ix_uom_category_lsn'), table_name='uom_category')
    op.drop_index(op.f('ix_uom_category_id'), table_name='uom_category')
    op.drop_index(op.f('ix_uom_category_company_id'), table_name='uom_category')
    op.drop_table('uom_category')
    op.drop_index(op.f('ix_store_lsn'), table_name='store')
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.drop_index(op.f('ix_store_company_id'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_role_permissions_allow'), table_name='role')
    op.drop_index(op.f('ix_role_parents'), table_name='role')
    op.drop_index(op.f('ix_role_lsn'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_company_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_company_title'), table_name='company')
    op.drop_index(op.f('ix_company_lsn'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
